
pub const TUI_BIRD_TITLE: &str = r#"
████████╗██╗   ██╗██╗    ████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
╚══██╔══╝██║   ██║██║    ╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
   ██║   ██║   ██║██║       ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║   
   ██║   ██║   ██║██║       ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║   
   ██║   ╚██████╔╝██║       ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║   
   ╚═╝    ╚═════╝ ╚═╝       ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝   
"#;

pub const TUI_LOGO: &str = r#"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx.     .xX$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:.:xXX Xx      .+XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;::XXX;   :X$$$XXXX$XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx:::xX:  :XX$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx::::+X+  .XXXXXX$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$XXXXXXXXXX$$XXXx:::::xX+   xXXXX$$XXX$$$XXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXX                 .:::::xXX.   +XXXXXx::::+XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXX                 .+xX$Xx     xXXXXXX;:::::XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXX                  :.       ;XXXXX$$XX+::;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$Xx      :X$$$$        .XX:....:X$      +XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx      :XXXXX        .XX::::::X$      +$XXXXXXXXXXXXXXXXXXXXXXXXX$$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx      :X$XX$        .XX::::::X$      +$XXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx      :XXXX$        .XX::::::X$      +$XXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx      :XXXX$        .XX::::::X$      +XXXXXXXXXXXXXXXXXXXXXXXXX$$$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx      :XXXX$        :XX::::::X$      +XXXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx      :XXXXX        +XX::::::X$      +XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       X$$$$.      +XX+:::::xX$      +XXXXXXXXXXXXXXXXXXXXXXXXXX$X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.       :X$$X.   +XXx::::::x$X$      +$XXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx            ++:::::::::x$$$X$      +XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+;::;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX+         xX:      ;XX;        :xX.        ;XX.        xX    +XXX   ;;         XXXXXXXXXXX
XXXXXXXXXx;;.   :;+:    ;:    x:   ;;;    +    ;;;    X    ;;;;;Xx      XX   :x;;.   ;;+XXXXXXXXXXX
XXXXXXXXXXXX;   xXX    XXXx   +:          X           X        :Xx   :   :   :XXX:   XXXXXXXXXXXXXX
XXXXXXXXXXXX;   xXX+    .     X:   ;;:    X    :;:   .X    .....;x   ;X+     :XXX:   XXXXXXXXXXXXXX
XXXXXXXXXXXX+  .xXXXX+.    :xXX+   XXXx   x:  :XXX+  .X:        :X   +XXX:   +XXX+  .XXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
"#;